scrape_config:
  address: "https://gnosisscan.io/"
  selector: "/html/body/div[1]/main/div/div[3]/div[1]/div/div/div/div[1]/div/div[1]/div[1]/div/div[2]/a"
  decimal_point_separator: "."
  thousands_separator: ","
  metric:
    name: gnosisscan_indexed_block
    type: gauge
    help: "Latest Indexed Block"
    labels:
      language: english

global_config:
  port: 9883
  metric_name_prefix: "htmlexporter_"
